# Generated by Django 4.2.20 on 2025-06-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='vip_price',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='tariff',
        ),
        migrations.AddField(
            model_name='game',
            name='table_count',
            field=models.IntegerField(default=1, verbose_name='Stollar soni'),
            preserve_default=False,
        ),
    ]
