# Generated by Django 4.2.20 on 2025-06-27 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_gamesession_end_time_game_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='hours',
            new_name='duration_hours',
        ),
    ]
