# Generated by Django 4.2.20 on 2025-06-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_hours_game_duration_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='duration_hours',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
